### ISSUE TITLE
-bash: runpsipred: command not found

### ISSUE THREAD

**Issue by addsg** [psipred/psipred#12] opened 2023-12-19 14:10 UTC
I met this problem as I want to use PSIPRED locally. 
![image](https://github.com/psipred/psipred/assets/97738331/4a71ebe7-3a82-47b5-ab41-1f6507045340)

**Comment by DanBuchan** [comment] 2024-01-02 15:56
I can't tell from the picture provided what the problem is. What command is not found?

**Comment by DanBuchan** [comment] 2024-01-29 12:29
As it is now over a month I'm closing this, please reopen if there is still an issue.,

**Closed as completed by DanBuchan** 2024-01-29 12:29 UTC
